### ISSUE TITLE
Error: Unrecognized option: --source-termino

### ISSUE THREAD

**Issue by OksanaMishchenko** [termsuite/termsuite-core#111]
Hello,
I'm trying to align my two sets of json format terminologies. But getting this error, could you tell me please what might go wrong? Using all relative paths.
Using Mac OS, running termsuite on java 10 with --add-modules java.xml.bind

Exception in thread "main" fr.univnantes.termsuite.tools.TermSuiteCliException: Could not parse arguments. Error: Unrecognized option: --source-termino
	at fr.univnantes.termsuite.tools.CommandLineClient.launch(CommandLineClient.java:292)
	at fr.univnantes.termsuite.tools.TerminologyExtractorCLI.main(TerminologyExtractorCLI.java:203)
Caused by: org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --source-termino
	at org.apache.commons.cli.Parser.processOption(Parser.java:363)
	at org.apache.commons.cli.Parser.parse(Parser.java:199)
	at org.apache.commons.cli.Parser.parse(Parser.java:85)
	at fr.univnantes.termsuite.tools.CommandLineClient.launch(CommandLineClient.java:274)
	... 1 more

Thanks in advance

**Comment by OksanaMishchenko** [comment]
Sorry, after checking for n-time my command found a typo
