### ISSUE TITLE
Bug in TermOccAnnotationImporter when termocc.pattern.size != termocc.words.size

### ISSUE THREAD

**Issue by dcram** [termsuite/termsuite-core#61]
```
Exception in thread "main" eu.project.ttc.engines.desc.TermSuitePipelineException: org.apache.uima.analysis_engine.AnalysisEngineProcessException: Annotator processing failed.   
    at eu.project.ttc.tools.TermSuitePipeline.runPipeline(TermSuitePipeline.java:338)
    at eu.project.ttc.tools.TermSuitePipeline.run(TermSuitePipeline.java:329)
    at eu.project.ttc.tools.cli.CLItest.main(CLItest.java:12)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.apache.uima.analysis_engine.AnalysisEngineProcessException: Annotator processing failed.   
    at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:401)
    at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:309)
    at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:569)
    at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:411)
    at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)
    at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:266)
    at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:569)
    at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:411)
    at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)
    at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:266)
    at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:267)
    at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:150)
    at eu.project.ttc.tools.TermSuitePipeline.runPipeline(TermSuitePipeline.java:335)
    ... 7 more
Caused by: LowLevelException: Error in low-level CAS APIs: array index out of range: 3.
    at org.apache.uima.jcas.impl.JCasImpl.checkArrayBounds(JCasImpl.java:1102)
    at eu.project.ttc.types.TermOccAnnotation.getPattern(TermOccAnnotation.java:154)
    at eu.project.ttc.utils.TermSuiteUtils.getGroupingKey(TermSuiteUtils.java:115)
    at eu.project.ttc.models.index.MemoryTermIndex.addTermOccurrence(MemoryTermIndex.java:168)
    at eu.project.ttc.engines.TermOccAnnotationImporter.process(TermOccAnnotationImporter.java:68)
    at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
    at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
    ... 19 more
```

**Comment by simonmeoni** [comment]
see pull request #65

**Comment by dcram** [comment]
Thx
