### ISSUE TITLE
Plug chinese segmenter

### ISSUE THREAD

**Issue by dcram** [termsuite/termsuite-core#73]
SEGMENT_BANK is missing for chinese. Needs to plug the old TermSuite 1.5 chinese segmenter.

```
Exception in thread "main" eu.project.ttc.engines.desc.TermSuitePipelineException: java.lang.NullPointerException: Failed to load resource SEGMENT_BANK. Url is null.
    at eu.project.ttc.tools.TermSuitePipeline.aeWordTokenizer(TermSuitePipeline.java:676)
    at eu.project.ttc.api.TerminoExtractor.execute(TerminoExtractor.java:307)
    at org.ttc.project.builder.TerminoExtractorLauncher.fromTxtCorpus(TerminoExtractorLauncher.java:58)
    at org.ttc.project.builder.TerminoExtractorLauncher.main(TerminoExtractorLauncher.java:36)
Caused by: java.lang.NullPointerException: Failed to load resource SEGMENT_BANK. Url is null.
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:251)
    at eu.project.ttc.tools.TermSuiteResource.checkUrl(TermSuiteResource.java:114)
    at eu.project.ttc.tools.TermSuiteResource.fromClasspath(TermSuiteResource.java:135)
    at eu.project.ttc.tools.TermSuitePipeline.getResUrl(TermSuitePipeline.java:771)
    at eu.project.ttc.tools.TermSuitePipeline.aeWordTokenizer(TermSuitePipeline.java:664)
    ... 3 more

```

**Comment by dcram** [comment]
Fixed, but linguistic resources in chinese are still poor and the output of terminology extraction in chinese is polluted.

For example, current top-10 terms extracted from wind energy corpus are:

```
"n: ないので",
"nn: _ vicinity",
"nn: _ ansi",
"nn: slope _",
"n: 動作",
"n: economic",
"nn: gpsprom watchdog",
"nn: _ うものです",
"nn: _ ジョイントボルト",
"n: srppq"
```
